/* PRB — AUTO-GENERATED by prb/scripts/build-books.mjs on 2026-07-22T22:26:55.330Z */
window.PRB = window.PRB || {};

PRB.users = {
  bian: { id: 'bian', name: 'Bian', handle: 'bianvepelis',    color: '#22D3EE', initial: 'B' },
  luke: { id: 'luke', name: 'Luke', handle: 'LukeLookMovies', color: '#3D7BFF', initial: 'L' },
};

PRB.books = [
  {
    "id": "1984-george-orwell",
    "title": "1984",
    "author": "George Orwell",
    "year": 1949,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Winston Smith vive bajo la vigilancia total del Gran Hermano y empieza a soñar con la libertad de pensar. La distopía definitiva sobre el poder y la verdad.",
    "cover": "https://covers.openlibrary.org/b/id/14351142-L.jpg",
    "featured": true
  },
  {
    "id": "brave-new-world-aldous-huxley",
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "year": 1932,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un mundo “feliz” de castas diseñadas, placer químico y libertad abolida. La cara amable —y más inquietante— del totalitarismo.",
    "cover": "https://covers.openlibrary.org/b/id/8231823-L.jpg",
    "featured": true
  },
  {
    "id": "fahrenheit-451-ray-bradbury",
    "title": "Fahrenheit 451",
    "author": "Ray Bradbury",
    "year": 1953,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un bombero cuya misión es quemar libros empieza a cuestionar el mundo sin memoria que ayuda a sostener.",
    "cover": "https://covers.openlibrary.org/b/id/12993656-L.jpg",
    "featured": true
  },
  {
    "id": "we-yevgueni-zamiatin",
    "title": "We",
    "author": "Yevgueni Zamiatin",
    "year": 1924,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En el Estado Único todos son números y la razón lo ordena todo, hasta que el amor irrumpe. La abuela de todas las distopías.",
    "cover": null,
    "featured": false
  },
  {
    "id": "the-handmaid-s-tale-margaret-atwood",
    "title": "The Handmaid’s Tale",
    "author": "Margaret Atwood",
    "year": 1985,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En la teocracia de Gilead las mujeres fértiles son propiedad del Estado. El relato de Offred, entre el terror y la resistencia.",
    "cover": "https://covers.openlibrary.org/b/id/8231851-L.jpg",
    "featured": true
  },
  {
    "id": "do-androids-dream-of-electric-sheep-philip-k-dick",
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "year": 1968,
    "genres": [
      "Ciencia ficción",
      "Distopía"
    ],
    "synopsis": "Un cazarrecompensas persigue androides indistinguibles de humanos y se pregunta qué nos hace, en el fondo, reales.",
    "cover": "https://covers.openlibrary.org/b/id/207515-L.jpg",
    "featured": true
  },
  {
    "id": "neuromancer-william-gibson",
    "title": "Neuromancer",
    "author": "William Gibson",
    "year": 1984,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "Un hacker quemado recibe un último trabajo imposible en el ciberespacio. El libro que fundó el cyberpunk.",
    "cover": "https://covers.openlibrary.org/b/id/283860-L.jpg",
    "featured": true
  },
  {
    "id": "snow-crash-neal-stephenson",
    "title": "Snow Crash",
    "author": "Neal Stephenson",
    "year": 1992,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "Un repartidor de pizzas y hacker persigue un virus que ataca tanto a las computadoras como a las mentes en el Metaverso.",
    "cover": "https://covers.openlibrary.org/b/id/392508-L.jpg",
    "featured": false
  },
  {
    "id": "the-dispossessed-ursula-k-le-guin",
    "title": "The Dispossessed",
    "author": "Ursula K. Le Guin",
    "year": 1974,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un físico viaja entre un mundo anarquista y otro capitalista buscando una teoría que los una. Utopía ambigua y brillante.",
    "cover": "https://covers.openlibrary.org/b/id/6979680-L.jpg",
    "featured": false
  },
  {
    "id": "a-clockwork-orange-anthony-burgess",
    "title": "A Clockwork Orange",
    "author": "Anthony Burgess",
    "year": 1962,
    "genres": [
      "Distopía",
      "Clásico"
    ],
    "synopsis": "Alex y su ultraviolencia, y el Estado que quiere “curarlo”. ¿Puede haber bondad sin libertad de elegir el mal?",
    "cover": "https://covers.openlibrary.org/b/id/13151224-L.jpg",
    "featured": false
  },
  {
    "id": "the-road-cormac-mccarthy",
    "title": "The Road",
    "author": "Cormac McCarthy",
    "year": 2006,
    "genres": [
      "Distopía",
      "Novela"
    ],
    "synopsis": "Un padre y su hijo cruzan una tierra arrasada por la ceniza, cargando el fuego de la esperanza. Devastador y luminoso.",
    "cover": "https://covers.openlibrary.org/b/id/198120-L.jpg",
    "featured": true
  },
  {
    "id": "never-let-me-go-kazuo-ishiguro",
    "title": "Never Let Me Go",
    "author": "Kazuo Ishiguro",
    "year": 2005,
    "genres": [
      "Ciencia ficción",
      "Novela"
    ],
    "synopsis": "Tres jóvenes en un internado inglés descubren de a poco el propósito terrible para el que fueron criados.",
    "cover": "https://covers.openlibrary.org/b/id/1047334-L.jpg",
    "featured": false
  },
  {
    "id": "the-man-in-the-high-castle-philip-k-dick",
    "title": "The Man in the High Castle",
    "author": "Philip K. Dick",
    "year": 1962,
    "genres": [
      "Ciencia ficción",
      "Distopía"
    ],
    "synopsis": "Una ucronía donde el Eje ganó la guerra, y un libro prohibido insinúa que la realidad podría ser otra.",
    "cover": "https://covers.openlibrary.org/b/id/420452-L.jpg",
    "featured": false
  },
  {
    "id": "parable-of-the-sower-octavia-e-butler",
    "title": "Parable of the Sower",
    "author": "Octavia E. Butler",
    "year": 1993,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En una California colapsada, una joven con hiperempatía funda una nueva fe para sobrevivir al derrumbe.",
    "cover": "https://covers.openlibrary.org/b/id/10466266-L.jpg",
    "featured": false
  },
  {
    "id": "oryx-and-crake-margaret-atwood",
    "title": "Oryx and Crake",
    "author": "Margaret Atwood",
    "year": 2003,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "El último humano recuerda cómo la ingeniería genética y la codicia llevaron al fin del mundo.",
    "cover": "https://covers.openlibrary.org/b/id/12507658-L.jpg",
    "featured": false
  },
  {
    "id": "station-eleven-emily-st-john-mandel",
    "title": "Station Eleven",
    "author": "Emily St. John Mandel",
    "year": 2014,
    "genres": [
      "Distopía",
      "Novela"
    ],
    "synopsis": "Tras una pandemia que borra la civilización, una troupe itinerante lleva a Shakespeare por los pueblos que quedan.",
    "cover": "https://covers.openlibrary.org/b/id/7369961-L.jpg",
    "featured": true
  },
  {
    "id": "the-children-of-men-p-d-james",
    "title": "The Children of Men",
    "author": "P. D. James",
    "year": 1992,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "La humanidad dejó de tener hijos y se apaga sin futuro, hasta que un embarazo lo cambia todo.",
    "cover": "https://covers.openlibrary.org/b/id/3218320-L.jpg",
    "featured": false
  },
  {
    "id": "slaughterhouse-five-kurt-vonnegut",
    "title": "Slaughterhouse-Five",
    "author": "Kurt Vonnegut",
    "year": 1969,
    "genres": [
      "Ciencia ficción",
      "Clásico",
      "Novela"
    ],
    "synopsis": "Billy Pilgrim quedó “desanclado” en el tiempo y revive el bombardeo de Dresde y su abducción alienígena. Así son las cosas.",
    "cover": "https://covers.openlibrary.org/b/id/12727001-L.jpg",
    "featured": false
  },
  {
    "id": "solaris-stanis-aw-lem",
    "title": "Solaris",
    "author": "Stanisław Lem",
    "year": 1961,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un océano-planeta consciente materializa los recuerdos más dolorosos de los científicos que lo estudian.",
    "cover": "https://covers.openlibrary.org/b/id/12313764-L.jpg",
    "featured": false
  },
  {
    "id": "dune-frank-herbert",
    "title": "Dune",
    "author": "Frank Herbert",
    "year": 1965,
    "genres": [
      "Ciencia ficción",
      "Aventura",
      "Clásico"
    ],
    "synopsis": "En el planeta desértico Arrakis, el joven Paul Atreides se convierte en el eje de una guerra por la especia y el destino.",
    "cover": "https://covers.openlibrary.org/b/id/11481354-L.jpg",
    "featured": true
  },
  {
    "id": "foundation-isaac-asimov",
    "title": "Foundation",
    "author": "Isaac Asimov",
    "year": 1951,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Hari Seldon predice la caída del Imperio Galáctico y crea una Fundación para acortar la edad oscura que viene.",
    "cover": "https://covers.openlibrary.org/b/id/14612610-L.jpg",
    "featured": false
  },
  {
    "id": "the-left-hand-of-darkness-ursula-k-le-guin",
    "title": "The Left Hand of Darkness",
    "author": "Ursula K. Le Guin",
    "year": 1969,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un enviado llega a un mundo helado donde el género no existe, y debe aprender a ver de nuevo lo humano.",
    "cover": "https://covers.openlibrary.org/b/id/10618463-L.jpg",
    "featured": false
  },
  {
    "id": "meditaciones-marco-aurelio",
    "title": "Meditaciones",
    "author": "Marco Aurelio",
    "year": 180,
    "genres": [
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "Los apuntes privados de un emperador estoico consigo mismo: cómo vivir con serenidad, deber y aceptación.",
    "cover": "https://covers.openlibrary.org/b/id/211529-L.jpg",
    "featured": true
  },
  {
    "id": "asi-hablo-zaratustra-friedrich-nietzsche",
    "title": "Así habló Zaratustra",
    "author": "Friedrich Nietzsche",
    "year": 1883,
    "genres": [
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "El profeta Zaratustra baja de la montaña a anunciar el superhombre, la muerte de Dios y el eterno retorno.",
    "cover": "https://covers.openlibrary.org/b/id/4969090-L.jpg",
    "featured": false
  },
  {
    "id": "el-mito-de-sisifo-albert-camus",
    "title": "El mito de Sísifo",
    "author": "Albert Camus",
    "year": 1942,
    "genres": [
      "Filosofía"
    ],
    "synopsis": "Si la vida es absurda, ¿por qué seguir? Camus responde con la rebeldía lúcida de Sísifo, feliz con su roca.",
    "cover": "https://covers.openlibrary.org/b/id/12726570-L.jpg",
    "featured": false
  },
  {
    "id": "el-extranjero-albert-camus",
    "title": "El extranjero",
    "author": "Albert Camus",
    "year": 1942,
    "genres": [
      "Filosofía",
      "Novela",
      "Clásico"
    ],
    "synopsis": "Meursault mata a un hombre bajo el sol y enfrenta a una sociedad que lo condena más por no fingir emociones.",
    "cover": null,
    "featured": false
  },
  {
    "id": "el-hombre-en-busca-de-sentido-viktor-frankl",
    "title": "El hombre en busca de sentido",
    "author": "Viktor Frankl",
    "year": 1946,
    "genres": [
      "Filosofía"
    ],
    "synopsis": "Un psiquiatra sobreviviente de los campos nazis explica cómo el sentido puede sostenernos en el peor sufrimiento.",
    "cover": "https://covers.openlibrary.org/b/id/465226-L.jpg",
    "featured": false
  },
  {
    "id": "crimen-y-castigo-fiodor-dostoievski",
    "title": "Crimen y castigo",
    "author": "Fiódor Dostoievski",
    "year": 1866,
    "genres": [
      "Novela",
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "Raskólnikov comete un asesinato para probar una teoría, y la culpa lo persigue más que cualquier ley.",
    "cover": "https://covers.openlibrary.org/b/id/13116014-L.jpg",
    "featured": true
  },
  {
    "id": "cien-anos-de-soledad-gabriel-garcia-marquez",
    "title": "Cien años de soledad",
    "author": "Gabriel García Márquez",
    "year": 1967,
    "genres": [
      "Novela",
      "Clásico"
    ],
    "synopsis": "La saga de los Buendía en Macondo, donde lo mágico y lo real conviven a lo largo de siete generaciones.",
    "cover": null,
    "featured": false
  },
  {
    "id": "el-maestro-y-margarita-mijail-bulgakov",
    "title": "El maestro y Margarita",
    "author": "Mijaíl Bulgákov",
    "year": 1967,
    "genres": [
      "Novela",
      "Fantasía",
      "Clásico"
    ],
    "synopsis": "El diablo visita la Moscú soviética con un séquito disparatado, mientras se cruza una historia de amor y de fe.",
    "cover": "https://covers.openlibrary.org/b/id/15013644-L.jpg",
    "featured": false
  },
  {
    "id": "un-mundo-feliz-revisitado-aldous-huxley",
    "title": "Un mundo feliz revisitado",
    "author": "Aldous Huxley",
    "year": 1958,
    "genres": [
      "Filosofía",
      "Ensayo"
    ],
    "synopsis": "Huxley vuelve sobre su distopía para ver cuánto de ella ya llegó: propaganda, consumo y control blando.",
    "cover": "https://covers.openlibrary.org/b/id/35568-L.jpg",
    "featured": false
  },
  {
    "id": "roadside-picnic-arkady-y-boris-strugatsky",
    "title": "Roadside Picnic",
    "author": "Arkady y Boris Strugatsky",
    "year": 1972,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Tras una visita alienígena quedan “Zonas” con objetos imposibles; los stalkers arriesgan la vida por rescatarlos.",
    "cover": "https://covers.openlibrary.org/b/id/6752719-L.jpg",
    "featured": false
  },
  {
    "id": "los-juegos-del-hambre-suzanne-collins",
    "title": "Los juegos del hambre",
    "author": "Suzanne Collins",
    "year": 2008,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Aventura"
    ],
    "synopsis": "En Panem, cada año dos jóvenes de cada distrito pelean a muerte por TV. Katniss se ofrece en lugar de su hermana y enciende una rebelión.",
    "cover": "https://covers.openlibrary.org/b/id/12646537-L.jpg",
    "featured": true
  },
  {
    "id": "en-llamas-suzanne-collins",
    "title": "En llamas",
    "author": "Suzanne Collins",
    "year": 2009,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "Katniss se volvió símbolo de la rebelión y el Capitolio responde con un Vasallaje que reúne a los vencedores en la arena.",
    "cover": "https://covers.openlibrary.org/b/id/12878880-L.jpg",
    "featured": false
  },
  {
    "id": "sinsajo-suzanne-collins",
    "title": "Sinsajo",
    "author": "Suzanne Collins",
    "year": 2010,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "La guerra abierta contra el Capitolio convierte a Katniss en el rostro de una revolución que también tiene su costado oscuro.",
    "cover": "https://covers.openlibrary.org/b/id/12646459-L.jpg",
    "featured": false
  },
  {
    "id": "divergente-veronica-roth",
    "title": "Divergente",
    "author": "Veronica Roth",
    "year": 2011,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "Una sociedad dividida en facciones por virtudes; Tris no encaja en ninguna y ese secreto la vuelve un peligro.",
    "cover": "https://covers.openlibrary.org/b/id/13274634-L.jpg",
    "featured": false
  },
  {
    "id": "el-corredor-del-laberinto-james-dashner",
    "title": "El corredor del laberinto",
    "author": "James Dashner",
    "year": 2009,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "Thomas despierta sin memoria en un claro rodeado por un laberinto mortal que cambia cada noche.",
    "cover": "https://covers.openlibrary.org/b/id/15139005-L.jpg",
    "featured": false
  },
  {
    "id": "ready-player-one-ernest-cline",
    "title": "Ready Player One",
    "author": "Ernest Cline",
    "year": 2011,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk",
      "Aventura"
    ],
    "synopsis": "En un futuro que vive dentro del OASIS, un cazatesoros nerd persigue el huevo de pascua que hereda un imperio virtual.",
    "cover": "https://covers.openlibrary.org/b/id/8737626-L.jpg",
    "featured": true
  },
  {
    "id": "el-marciano-andy-weir",
    "title": "El marciano",
    "author": "Andy Weir",
    "year": 2011,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Un astronauta queda varado y dado por muerto en Marte y usa ciencia, humor y papas para sobrevivir.",
    "cover": "https://covers.openlibrary.org/b/id/11447888-L.jpg",
    "featured": true
  },
  {
    "id": "proyecto-hail-mary-andy-weir",
    "title": "Proyecto Hail Mary",
    "author": "Andy Weir",
    "year": 2021,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Un hombre despierta solo en una nave sin recordar quién es, y descubre que carga la última esperanza de la Tierra.",
    "cover": "https://covers.openlibrary.org/b/id/11200092-L.jpg",
    "featured": true
  },
  {
    "id": "el-problema-de-los-tres-cuerpos-liu-cixin",
    "title": "El problema de los tres cuerpos",
    "author": "Liu Cixin",
    "year": 2008,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Un videojuego imposible y una señal del espacio revelan un primer contacto que pone en jaque a toda la humanidad.",
    "cover": "https://covers.openlibrary.org/b/id/10526598-L.jpg",
    "featured": true
  },
  {
    "id": "el-juego-de-ender-orson-scott-card",
    "title": "El juego de Ender",
    "author": "Orson Scott Card",
    "year": 1985,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un niño prodigio es entrenado en una escuela de guerra orbital para liderar a la humanidad contra una raza alienígena.",
    "cover": "https://covers.openlibrary.org/b/id/12996033-L.jpg",
    "featured": false
  },
  {
    "id": "hyperion-dan-simmons",
    "title": "Hyperion",
    "author": "Dan Simmons",
    "year": 1989,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Siete peregrinos viajan hacia las Tumbas del Tiempo y la criatura Alcaudón, contando cada uno su historia como en Canterbury.",
    "cover": "https://covers.openlibrary.org/b/id/380332-L.jpg",
    "featured": false
  },
  {
    "id": "carbono-modificado-richard-k-morgan",
    "title": "Carbono modificado",
    "author": "Richard K. Morgan",
    "year": 2002,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "En un futuro donde la mente se descarga en cuerpos intercambiables, un ex soldado investiga la “muerte” de un millonario.",
    "cover": "https://covers.openlibrary.org/b/id/13223488-L.jpg",
    "featured": false
  },
  {
    "id": "amanecer-rojo-pierce-brown",
    "title": "Amanecer rojo",
    "author": "Pierce Brown",
    "year": 2014,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En una Marte de castas de colores, un minero de la casta más baja se infiltra entre los Dorados para derribar el sistema.",
    "cover": "https://covers.openlibrary.org/b/id/7316188-L.jpg",
    "featured": false
  },
  {
    "id": "siega-neal-shusterman",
    "title": "Siega",
    "author": "Neal Shusterman",
    "year": 2016,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En un mundo sin muerte natural, unos “segadores” deciden quién muere; dos aprendices cuestionan ese poder absoluto.",
    "cover": "https://covers.openlibrary.org/b/id/8184999-L.jpg",
    "featured": false
  },
  {
    "id": "klara-y-el-sol-kazuo-ishiguro",
    "title": "Klara y el Sol",
    "author": "Kazuo Ishiguro",
    "year": 2021,
    "genres": [
      "Ciencia ficción",
      "Novela"
    ],
    "synopsis": "Klara, una amiga artificial que adora al Sol, observa el amor y la soledad humanas desde la vidriera de una tienda.",
    "cover": "https://covers.openlibrary.org/b/id/10648686-L.jpg",
    "featured": false
  },
  {
    "id": "materia-oscura-blake-crouch",
    "title": "Materia oscura",
    "author": "Blake Crouch",
    "year": 2016,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Un físico es secuestrado por una versión de sí mismo y arrojado a un multiverso donde debe encontrar el camino a su vida.",
    "cover": "https://covers.openlibrary.org/b/id/7436634-L.jpg",
    "featured": false
  },
  {
    "id": "recursion-blake-crouch",
    "title": "Recursión",
    "author": "Blake Crouch",
    "year": 2019,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Una tecnología para revivir recuerdos empieza a reescribir la realidad y la memoria colectiva colapsa.",
    "cover": "https://covers.openlibrary.org/b/id/8748478-L.jpg",
    "featured": false
  },
  {
    "id": "ubik-philip-k-dick",
    "title": "Ubik",
    "author": "Philip K. Dick",
    "year": 1969,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Tras una explosión, un equipo de anti-psíquicos ve el mundo degradarse y el tiempo retroceder. ¿Quién está vivo?",
    "cover": "https://covers.openlibrary.org/b/id/5018327-L.jpg",
    "featured": false
  },
  {
    "id": "el-fin-de-la-infancia-arthur-c-clarke",
    "title": "El fin de la infancia",
    "author": "Arthur C. Clarke",
    "year": 1953,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Unos “Superseñores” traen paz a la Tierra, pero el precio es el destino final de la especie humana.",
    "cover": "https://covers.openlibrary.org/b/id/210200-L.jpg",
    "featured": false
  },
  {
    "id": "2001-una-odisea-espacial-arthur-c-clarke",
    "title": "2001: Una odisea espacial",
    "author": "Arthur C. Clarke",
    "year": 1968,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "De un monolito en la prehistoria a HAL 9000 y más allá de Júpiter: el salto evolutivo de la humanidad.",
    "cover": "https://covers.openlibrary.org/b/id/15170836-L.jpg",
    "featured": true
  },
  {
    "id": "la-maquina-del-tiempo-h-g-wells",
    "title": "La máquina del tiempo",
    "author": "H. G. Wells",
    "year": 1895,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un viajero llega a un futuro lejano donde la humanidad se dividió en dos especies, y descubre el fin de la Tierra.",
    "cover": "https://covers.openlibrary.org/b/id/9009316-L.jpg",
    "featured": false
  },
  {
    "id": "akira-katsuhiro-otomo",
    "title": "Akira",
    "author": "Katsuhiro Otomo",
    "year": 1982,
    "genres": [
      "Manga",
      "Ciencia ficción",
      "Cyberpunk",
      "Distopía"
    ],
    "synopsis": "En Neo-Tokio, poderes psíquicos y una moto roja desatan el caos. La obra cumbre del manga cyberpunk.",
    "cover": "https://covers.openlibrary.org/b/id/814967-L.jpg",
    "featured": true
  },
  {
    "id": "ghost-in-the-shell-masamune-shirow",
    "title": "Ghost in the Shell",
    "author": "Masamune Shirow",
    "year": 1989,
    "genres": [
      "Manga",
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "La mayor Kusanagi, cuerpo cibernético y mente humana, persigue a un hacker que borra la línea entre alma y máquina.",
    "cover": "https://covers.openlibrary.org/b/id/869285-L.jpg",
    "featured": false
  },
  {
    "id": "nausicaa-del-valle-del-viento-hayao-miyazaki",
    "title": "Nausicaä del Valle del Viento",
    "author": "Hayao Miyazaki",
    "year": 1982,
    "genres": [
      "Manga",
      "Ciencia ficción",
      "Distopía",
      "Fantasía"
    ],
    "synopsis": "En una Tierra arrasada por un bosque tóxico, una princesa busca la armonía entre humanos y naturaleza.",
    "cover": "https://covers.openlibrary.org/b/id/813448-L.jpg",
    "featured": true
  },
  {
    "id": "alita-angel-de-combate-yukito-kishiro",
    "title": "Alita: Ángel de combate",
    "author": "Yukito Kishiro",
    "year": 1990,
    "genres": [
      "Manga",
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "Una ciborg amnésica rescatada de un basural busca su identidad en una ciudad chatarra brutal.",
    "cover": "https://covers.openlibrary.org/b/id/813408-L.jpg",
    "featured": false
  },
  {
    "id": "20th-century-boys-naoki-urasawa",
    "title": "20th Century Boys",
    "author": "Naoki Urasawa",
    "year": 1999,
    "genres": [
      "Manga",
      "Ciencia ficción",
      "Suspense"
    ],
    "synopsis": "Un grupo de amigos descubre que un culto está cumpliendo, punto por punto, la profecía apocalíptica que inventaron de chicos.",
    "cover": "https://covers.openlibrary.org/b/id/10521307-L.jpg",
    "featured": false
  },
  {
    "id": "pluto-naoki-urasawa",
    "title": "Pluto",
    "author": "Naoki Urasawa",
    "year": 2003,
    "genres": [
      "Manga",
      "Ciencia ficción"
    ],
    "synopsis": "Un detective robot investiga el asesinato de los robots más avanzados del mundo, en un thriller sobre qué nos hace humanos.",
    "cover": "https://covers.openlibrary.org/b/id/11297281-L.jpg",
    "featured": false
  },
  {
    "id": "your-name-makoto-shinkai",
    "title": "Your Name",
    "author": "Makoto Shinkai",
    "year": 2016,
    "genres": [
      "Novela",
      "Fantasía",
      "Manga"
    ],
    "synopsis": "Dos adolescentes que no se conocen empiezan a intercambiar cuerpos, y una catástrofe los une a través del tiempo.",
    "cover": "https://covers.openlibrary.org/b/id/10846610-L.jpg",
    "featured": true
  },
  {
    "id": "haikyu-haruichi-furudate",
    "title": "Haikyu!!",
    "author": "Haruichi Furudate",
    "year": 2012,
    "genres": [
      "Manga",
      "Deporte"
    ],
    "synopsis": "Un chico bajito con un salto imposible sueña con conquistar el vóley junto a un armador genial y rival.",
    "cover": null,
    "featured": false
  }
];

PRB.build = {"version":"1.2","built":"2026-07-23T06:45:47.982Z"};
