/* PRB — AUTO-GENERATED by prb/scripts/build-books.mjs on 2026-07-22T21:40:10.887Z */
window.PRB = window.PRB || {};

PRB.users = {
  bian: { id: 'bian', name: 'Bian', handle: 'bianvepelis',    color: '#22D3EE', initial: 'B' },
  luke: { id: 'luke', name: 'Luke', handle: 'LukeLookMovies', color: '#3D7BFF', initial: 'L' },
};

PRB.books = [
  {
    "id": "1984-george-orwell",
    "title": "1984",
    "author": "George Orwell",
    "year": 1949,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Winston Smith vive bajo la vigilancia total del Gran Hermano y empieza a soñar con la libertad de pensar. La distopía definitiva sobre el poder y la verdad.",
    "cover": "https://covers.openlibrary.org/b/id/8745958-L.jpg",
    "featured": true
  },
  {
    "id": "brave-new-world-aldous-huxley",
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "year": 1932,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un mundo “feliz” de castas diseñadas, placer químico y libertad abolida. La cara amable —y más inquietante— del totalitarismo.",
    "cover": "https://covers.openlibrary.org/b/id/8231823-L.jpg",
    "featured": true
  },
  {
    "id": "fahrenheit-451-ray-bradbury",
    "title": "Fahrenheit 451",
    "author": "Ray Bradbury",
    "year": 1953,
    "genres": [
      "Distopía",
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Un bombero cuya misión es quemar libros empieza a cuestionar el mundo sin memoria que ayuda a sostener.",
    "cover": "https://covers.openlibrary.org/b/id/12993656-L.jpg",
    "featured": true
  },
  {
    "id": "we-yevgueni-zamiatin",
    "title": "We",
    "author": "Yevgueni Zamiatin",
    "year": 1924,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En el Estado Único todos son números y la razón lo ordena todo, hasta que el amor irrumpe. La abuela de todas las distopías.",
    "cover": null,
    "featured": false
  },
  {
    "id": "the-handmaid-s-tale-margaret-atwood",
    "title": "The Handmaid’s Tale",
    "author": "Margaret Atwood",
    "year": 1985,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En la teocracia de Gilead las mujeres fértiles son propiedad del Estado. El relato de Offred, entre el terror y la resistencia.",
    "cover": "https://covers.openlibrary.org/b/id/8231851-L.jpg",
    "featured": true
  },
  {
    "id": "do-androids-dream-of-electric-sheep-philip-k-dick",
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "year": 1968,
    "genres": [
      "Ciencia ficción",
      "Distopía"
    ],
    "synopsis": "Un cazarrecompensas persigue androides indistinguibles de humanos y se pregunta qué nos hace, en el fondo, reales.",
    "cover": "https://covers.openlibrary.org/b/id/207515-L.jpg",
    "featured": true
  },
  {
    "id": "neuromancer-william-gibson",
    "title": "Neuromancer",
    "author": "William Gibson",
    "year": 1984,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "Un hacker quemado recibe un último trabajo imposible en el ciberespacio. El libro que fundó el cyberpunk.",
    "cover": "https://covers.openlibrary.org/b/id/283860-L.jpg",
    "featured": true
  },
  {
    "id": "snow-crash-neal-stephenson",
    "title": "Snow Crash",
    "author": "Neal Stephenson",
    "year": 1992,
    "genres": [
      "Ciencia ficción",
      "Cyberpunk"
    ],
    "synopsis": "Un repartidor de pizzas y hacker persigue un virus que ataca tanto a las computadoras como a las mentes en el Metaverso.",
    "cover": "https://covers.openlibrary.org/b/id/392508-L.jpg",
    "featured": false
  },
  {
    "id": "the-dispossessed-ursula-k-le-guin",
    "title": "The Dispossessed",
    "author": "Ursula K. Le Guin",
    "year": 1974,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un físico viaja entre un mundo anarquista y otro capitalista buscando una teoría que los una. Utopía ambigua y brillante.",
    "cover": "https://covers.openlibrary.org/b/id/6979680-L.jpg",
    "featured": false
  },
  {
    "id": "a-clockwork-orange-anthony-burgess",
    "title": "A Clockwork Orange",
    "author": "Anthony Burgess",
    "year": 1962,
    "genres": [
      "Distopía",
      "Clásico"
    ],
    "synopsis": "Alex y su ultraviolencia, y el Estado que quiere “curarlo”. ¿Puede haber bondad sin libertad de elegir el mal?",
    "cover": "https://covers.openlibrary.org/b/id/13151224-L.jpg",
    "featured": false
  },
  {
    "id": "the-road-cormac-mccarthy",
    "title": "The Road",
    "author": "Cormac McCarthy",
    "year": 2006,
    "genres": [
      "Distopía",
      "Novela"
    ],
    "synopsis": "Un padre y su hijo cruzan una tierra arrasada por la ceniza, cargando el fuego de la esperanza. Devastador y luminoso.",
    "cover": "https://covers.openlibrary.org/b/id/198120-L.jpg",
    "featured": true
  },
  {
    "id": "never-let-me-go-kazuo-ishiguro",
    "title": "Never Let Me Go",
    "author": "Kazuo Ishiguro",
    "year": 2005,
    "genres": [
      "Ciencia ficción",
      "Novela"
    ],
    "synopsis": "Tres jóvenes en un internado inglés descubren de a poco el propósito terrible para el que fueron criados.",
    "cover": "https://covers.openlibrary.org/b/id/1047334-L.jpg",
    "featured": false
  },
  {
    "id": "the-man-in-the-high-castle-philip-k-dick",
    "title": "The Man in the High Castle",
    "author": "Philip K. Dick",
    "year": 1962,
    "genres": [
      "Ciencia ficción",
      "Distopía"
    ],
    "synopsis": "Una ucronía donde el Eje ganó la guerra, y un libro prohibido insinúa que la realidad podría ser otra.",
    "cover": "https://covers.openlibrary.org/b/id/420452-L.jpg",
    "featured": false
  },
  {
    "id": "parable-of-the-sower-octavia-e-butler",
    "title": "Parable of the Sower",
    "author": "Octavia E. Butler",
    "year": 1993,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "En una California colapsada, una joven con hiperempatía funda una nueva fe para sobrevivir al derrumbe.",
    "cover": "https://covers.openlibrary.org/b/id/10466266-L.jpg",
    "featured": false
  },
  {
    "id": "oryx-and-crake-margaret-atwood",
    "title": "Oryx and Crake",
    "author": "Margaret Atwood",
    "year": 2003,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "El último humano recuerda cómo la ingeniería genética y la codicia llevaron al fin del mundo.",
    "cover": "https://covers.openlibrary.org/b/id/12507658-L.jpg",
    "featured": false
  },
  {
    "id": "station-eleven-emily-st-john-mandel",
    "title": "Station Eleven",
    "author": "Emily St. John Mandel",
    "year": 2014,
    "genres": [
      "Distopía",
      "Novela"
    ],
    "synopsis": "Tras una pandemia que borra la civilización, una troupe itinerante lleva a Shakespeare por los pueblos que quedan.",
    "cover": "https://covers.openlibrary.org/b/id/7369961-L.jpg",
    "featured": true
  },
  {
    "id": "the-children-of-men-p-d-james",
    "title": "The Children of Men",
    "author": "P. D. James",
    "year": 1992,
    "genres": [
      "Distopía",
      "Ciencia ficción"
    ],
    "synopsis": "La humanidad dejó de tener hijos y se apaga sin futuro, hasta que un embarazo lo cambia todo.",
    "cover": "https://covers.openlibrary.org/b/id/3218320-L.jpg",
    "featured": false
  },
  {
    "id": "slaughterhouse-five-kurt-vonnegut",
    "title": "Slaughterhouse-Five",
    "author": "Kurt Vonnegut",
    "year": 1969,
    "genres": [
      "Ciencia ficción",
      "Clásico",
      "Novela"
    ],
    "synopsis": "Billy Pilgrim quedó “desanclado” en el tiempo y revive el bombardeo de Dresde y su abducción alienígena. Así son las cosas.",
    "cover": "https://covers.openlibrary.org/b/id/12727001-L.jpg",
    "featured": false
  },
  {
    "id": "solaris-stanis-aw-lem",
    "title": "Solaris",
    "author": "Stanisław Lem",
    "year": 1961,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un océano-planeta consciente materializa los recuerdos más dolorosos de los científicos que lo estudian.",
    "cover": "https://covers.openlibrary.org/b/id/12313764-L.jpg",
    "featured": false
  },
  {
    "id": "dune-frank-herbert",
    "title": "Dune",
    "author": "Frank Herbert",
    "year": 1965,
    "genres": [
      "Ciencia ficción",
      "Aventura",
      "Clásico"
    ],
    "synopsis": "En el planeta desértico Arrakis, el joven Paul Atreides se convierte en el eje de una guerra por la especia y el destino.",
    "cover": "https://covers.openlibrary.org/b/id/11481354-L.jpg",
    "featured": true
  },
  {
    "id": "foundation-isaac-asimov",
    "title": "Foundation",
    "author": "Isaac Asimov",
    "year": 1951,
    "genres": [
      "Ciencia ficción",
      "Clásico"
    ],
    "synopsis": "Hari Seldon predice la caída del Imperio Galáctico y crea una Fundación para acortar la edad oscura que viene.",
    "cover": "https://covers.openlibrary.org/b/id/14612610-L.jpg",
    "featured": false
  },
  {
    "id": "the-left-hand-of-darkness-ursula-k-le-guin",
    "title": "The Left Hand of Darkness",
    "author": "Ursula K. Le Guin",
    "year": 1969,
    "genres": [
      "Ciencia ficción",
      "Filosofía"
    ],
    "synopsis": "Un enviado llega a un mundo helado donde el género no existe, y debe aprender a ver de nuevo lo humano.",
    "cover": "https://covers.openlibrary.org/b/id/10618463-L.jpg",
    "featured": false
  },
  {
    "id": "meditaciones-marco-aurelio",
    "title": "Meditaciones",
    "author": "Marco Aurelio",
    "year": 180,
    "genres": [
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "Los apuntes privados de un emperador estoico consigo mismo: cómo vivir con serenidad, deber y aceptación.",
    "cover": "https://covers.openlibrary.org/b/id/10469464-L.jpg",
    "featured": true
  },
  {
    "id": "asi-hablo-zaratustra-friedrich-nietzsche",
    "title": "Así habló Zaratustra",
    "author": "Friedrich Nietzsche",
    "year": 1883,
    "genres": [
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "El profeta Zaratustra baja de la montaña a anunciar el superhombre, la muerte de Dios y el eterno retorno.",
    "cover": "https://covers.openlibrary.org/b/id/2290835-L.jpg",
    "featured": false
  },
  {
    "id": "el-mito-de-sisifo-albert-camus",
    "title": "El mito de Sísifo",
    "author": "Albert Camus",
    "year": 1942,
    "genres": [
      "Filosofía"
    ],
    "synopsis": "Si la vida es absurda, ¿por qué seguir? Camus responde con la rebeldía lúcida de Sísifo, feliz con su roca.",
    "cover": null,
    "featured": false
  },
  {
    "id": "el-extranjero-albert-camus",
    "title": "El extranjero",
    "author": "Albert Camus",
    "year": 1942,
    "genres": [
      "Filosofía",
      "Novela",
      "Clásico"
    ],
    "synopsis": "Meursault mata a un hombre bajo el sol y enfrenta a una sociedad que lo condena más por no fingir emociones.",
    "cover": null,
    "featured": false
  },
  {
    "id": "el-hombre-en-busca-de-sentido-viktor-frankl",
    "title": "El hombre en busca de sentido",
    "author": "Viktor Frankl",
    "year": 1946,
    "genres": [
      "Filosofía"
    ],
    "synopsis": "Un psiquiatra sobreviviente de los campos nazis explica cómo el sentido puede sostenernos en el peor sufrimiento.",
    "cover": null,
    "featured": false
  },
  {
    "id": "crimen-y-castigo-fiodor-dostoievski",
    "title": "Crimen y castigo",
    "author": "Fiódor Dostoievski",
    "year": 1866,
    "genres": [
      "Novela",
      "Filosofía",
      "Clásico"
    ],
    "synopsis": "Raskólnikov comete un asesinato para probar una teoría, y la culpa lo persigue más que cualquier ley.",
    "cover": "https://covers.openlibrary.org/b/id/12328823-L.jpg",
    "featured": true
  },
  {
    "id": "cien-anos-de-soledad-gabriel-garcia-marquez",
    "title": "Cien años de soledad",
    "author": "Gabriel García Márquez",
    "year": 1967,
    "genres": [
      "Novela",
      "Clásico"
    ],
    "synopsis": "La saga de los Buendía en Macondo, donde lo mágico y lo real conviven a lo largo de siete generaciones.",
    "cover": "https://covers.openlibrary.org/b/id/12627383-L.jpg",
    "featured": true
  },
  {
    "id": "el-maestro-y-margarita-mijail-bulgakov",
    "title": "El maestro y Margarita",
    "author": "Mijaíl Bulgákov",
    "year": 1967,
    "genres": [
      "Novela",
      "Fantasía",
      "Clásico"
    ],
    "synopsis": "El diablo visita la Moscú soviética con un séquito disparatado, mientras se cruza una historia de amor y de fe.",
    "cover": null,
    "featured": false
  },
  {
    "id": "un-mundo-feliz-revisitado-aldous-huxley",
    "title": "Un mundo feliz revisitado",
    "author": "Aldous Huxley",
    "year": 1958,
    "genres": [
      "Filosofía",
      "Ensayo"
    ],
    "synopsis": "Huxley vuelve sobre su distopía para ver cuánto de ella ya llegó: propaganda, consumo y control blando.",
    "cover": null,
    "featured": false
  },
  {
    "id": "roadside-picnic-arkady-y-boris-strugatsky",
    "title": "Roadside Picnic",
    "author": "Arkady y Boris Strugatsky",
    "year": 1972,
    "genres": [
      "Ciencia ficción"
    ],
    "synopsis": "Tras una visita alienígena quedan “Zonas” con objetos imposibles; los stalkers arriesgan la vida por rescatarlos.",
    "cover": null,
    "featured": false
  }
];

PRB.build = {"version":"1.0","built":"2026-07-22T21:40:10.888Z"};
